.\" Manpage for FreeCell.
.\" Contact anton2920@gmail.com for comments or help.
.TH man 1 "21 Jan 2020" "1.0" "FreeCell man page"
.SH NAME
FreeCell
.SH SYNOPSIS
FreeCell
.SH DESCRIPTION
FreeCell is a clone of the famous Microsoft Windows game.
.SH OPTIONS
FreeCell takes no arguments
.SH BUGS
No known bugs.
.SH AUTHOR
anton2920 (anton2920@gmail.com)
